### ISSUE TITLE
Images broken on git clone

### ISSUE THREAD

**Issue by wSedlacek** [shadowfox87/YGOTCGOCGPicsNoBG#1]
Trying to clone this via git clone just leaves me stuck on Checking out 2%.
If I download via zip on github I get a zip that only has a few good images, most of them however are 131 bits and are not good.

Gonna try to fork and see what happens on my side.

**Comment by wSedlacek** [comment]
Same result:
git clone log
https://hastebin.com/dokuyagacu.erl

Download zip from github
https://drive.google.com/file/d/0B8n7y1UzZpMPUTFmZUJuNnEzVms/view?usp=sharing

**Comment by wSedlacek** [comment]
Looking into which files do and do not work it seems to be the files stored with the github lfs. I tried installing git lfs, and running "git lfs install" before cloneing to no avail.

**Comment by wSedlacek** [comment]
Tried cloning via ssh and via the github application got stuck on Checkingout 2% 115/5107 on both of them.

**Comment by wSedlacek** [comment]
Yea I am sure its the lfs, I am not sure how yall have it setup but to download these other than by making a script to download them one by one via links like I have bellow, I will need the settings you all are using for the lfs. Seems like I just need the custom url you are using.

**Comment by wSedlacek** [comment]
https://media.githubusercontent.com/media/shadowfox87/YGOTCGOCGPicsNoBG/master/10000000.png

**Comment by wSedlacek** [comment]
Looked into lfs some more and tried cloning with this command.
git lfs clone git@github.com:shadowfox87/YGOTCGOCGPicsNoBG.git

I got the full list of images however they were all the 131byte images and the command hung after checking out
https://hastebin.com/uzepahaxak.erl

Looking inside one of the 131byte "png"s with a text editor I find this:
https://hastebin.com/wokusuwasi.nginx

Navigating to https://git-lfs.github.com/spec/v1 is a 404 page and the hostname is just the download link for lfs.

**Comment by wSedlacek** [comment]
Here is the return of git lfs env:

https://hastebin.com/xoviwonugo.tex

**Comment by wSedlacek** [comment]
Figured out a work around. Ran that git lfs clone, let it checkout then pressed ctrl + C when it got stuck to move it to the lfs download step.

Alternatively I could of run git lfs pull it looks like to have fixed it.
Here is the information that led me to this:
https://developer.atlassian.com/blog/2016/04/git-lfs-12-clone-faster/

This still is gonna be an issue for most people downloading these however I found away around it for me.

**Comment by shadowfox87** [comment]
Yea I recently had to transfer all filled to git lfs because my repos were getting too big so GitHub staff actually told me to do it. Cloning from a git lfs should be possible. Im sure it is documented somewhere.

**Comment by wSedlacek** [comment]
It is possible. But not straight forward. What you could do is create a 7z file compressed @ Ultra and upload that along side the images. Or you could just get anti meta man to upload to his megaload sever where he is hosting all the other images. But getting these images is very difficult. Honestly I don't have a good solution but as it stands I can see 98% of people having problems downloading from the lfs.

**Comment by wSedlacek** [comment]
here is a compressed 7z of the close ups for anyone who finds this and is looking.
https://drive.google.com/file/d/0B8n7y1UzZpMPUGtuMDZiVVRDR0U/view?usp=sharing

I tried to fork however the upload keeps failing with "fatal: The remote end hung up unexpectedly" Increased the http bugger as far as it will go and still getting it.

**Comment by shadowfox87** [comment]
fyi, I am antimetaman. Use this for clone: https://developer.atlassian.com/blog/2016/04/git-lfs-12-clone-faster/

**Comment by wSedlacek** [comment]
Learn something new everyday.
